# Generated by Django 4.2.3 on 2023-07-28 03:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0003_subscribedusers_video_paidblogpost_book"),
    ]

    operations = [
        migrations.AddField(
            model_name="book",
            name="pdf_file",
            field=models.FileField(blank=True, null=True, upload_to="books/"),
        ),
    ]
