# Generated by Django 4.2.3 on 2023-07-28 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0004_book_pdf_file"),
    ]

    operations = [
        migrations.CreateModel(
            name="Resource",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("description", models.TextField()),
                ("file", models.FileField(upload_to="resources/")),
                (
                    "resource_type",
                    models.CharField(
                        choices=[
                            ("ebook", "E-Book"),
                            ("video", "Video"),
                            ("pdf", "PDF"),
                            ("article", "Article"),
                            ("picture", "Picture"),
                            ("software", "Software"),
                            ("tutorial", "Tutorial"),
                            ("audio", "Audio"),
                        ],
                        max_length=10,
                    ),
                ),
                ("price", models.DecimalField(decimal_places=2, max_digits=6)),
            ],
        ),
        migrations.RemoveField(
            model_name="paidblogpost",
            name="owner",
        ),
        migrations.RemoveField(
            model_name="video",
            name="owner",
        ),
        migrations.DeleteModel(
            name="Book",
        ),
        migrations.DeleteModel(
            name="PaidBlogPost",
        ),
        migrations.DeleteModel(
            name="Video",
        ),
    ]
