# Generated by Django 4.2.3 on 2023-08-01 15:03

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0007_cart_cartitem_remove_subscription_user_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="blogpost",
            name="content",
            field=ckeditor.fields.RichTextField(),
        ),
    ]
