# Generated by Django 4.2.3 on 2023-08-01 16:03

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0008_alter_blogpost_content"),
    ]

    operations = [
        migrations.AlterField(
            model_name="resource",
            name="description",
            field=ckeditor.fields.RichTextField(),
        ),
    ]
